# Generated by Django 3.1.2 on 2020-12-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSC_Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('chapter_name', models.CharField(max_length=50)),
                ('chapter_no', models.CharField(max_length=2)),
                ('question', models.CharField(max_length=300)),
                ('a', models.CharField(max_length=50)),
                ('b', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=50)),
                ('d', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
    ]
