# Generated by Django 3.1.2 on 2020-12-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsc_quiz',
            name='a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hsc_quiz',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hsc_quiz',
            name='b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hsc_quiz',
            name='c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hsc_quiz',
            name='d',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hsc_quiz',
            name='question',
            field=models.CharField(max_length=400),
        ),
    ]
