# Generated by Django 3.1.2 on 2020-12-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201222_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsc_quiz',
            name='Stimulating',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hsc_quiz',
            name='multiple_answer',
            field=models.TextField(blank=True),
        ),
    ]
