# Generated by Django 3.1.2 on 2020-12-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201222_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hsc_quiz',
            old_name='Stimulating',
            new_name='stimulation',
        ),
    ]
