# Generated by Django 3.1.2 on 2021-01-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_guest_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsc_quiz',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
