# Generated by Django 3.1.2 on 2021-01-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210102_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsc_quiz',
            name='chapter_no',
            field=models.CharField(blank=True, choices=[(1, 2), (4, 4)], max_length=2),
        ),
    ]
