# Generated by Django 3.1.2 on 2021-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210103_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsc_quiz',
            name='chapter_no',
            field=models.CharField(blank=True, choices=[('০১', '০১'), ('০২', '০২'), ('০৩', '০৩'), ('০৪', '০৪'), ('০৫', '০৫'), ('০৬', '০৬'), ('০৭', '০৭'), ('০৮', '০৮'), ('০৯', '০৯'), ('১০', '১০')], max_length=2),
        ),
    ]
