# Generated by Django 3.1.2 on 2021-01-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50)),
                ('formal_name', models.CharField(max_length=50)),
                ('chap_no_name', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
