# Generated by Django 3.1.2 on 2021-01-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20210103_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest_Quiz',
        ),
    ]
