# Generated by Django 3.1.2 on 2021-01-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_delete_guest_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='chap_no_name',
            new_name='chap_name',
        ),
    ]
