# Generated by Django 3.1.2 on 2021-01-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20210106_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='chap_name',
            new_name='chap_names',
        ),
    ]
