# Generated by Django 3.1.2 on 2020-12-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HSC_Biology_1st',
            new_name='HSC_Biology_1st_Note',
        ),
    ]
