# Generated by Django 3.1.2 on 2021-01-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_history',
            name='ip',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='visitor_history',
            name='path',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
